version: 2.1

jobs:
  build-and-test:
    working_directory: ~/test-repository/isa
    docker:
      - image: cimg/openjdk:17.0
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        auth:
          username: nikolaivanovic
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          name: deploy-server
          app-name: fishing-booker-app
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          name: deploy-client
          app-name: fishing-booker-client
          requires:
            - deploy-server