version: 2.1

jobs:
  build-and-test:
    working_directory: ~/test-repository/isa
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: nikolaivanovic
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: jpa  
    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=Ra1-2018_fishing-booker

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          name: deploy-server
          app-name: fishing-booker-app
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          name: deploy-client
          app-name: fishing-booker-client
          requires:
            - deploy-server