version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

jobs:
  build-and-test:
    working_directory: ~/test-repository/isa
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

orbs:
  heroku: circleci/heroku@1.2.6
  maven: circleci/maven@1.3.0
workflows:
  heroku_deploy:
    jobs:
      - build-and-test:
          executor: java17
      - heroku/deploy-via-git:
          requires:
            - build-and-test