version: 2.1

jobs:
  build-and-test:
    working_directory: ~/test-repository/isa
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jpa
    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          name: deploy-server
          app-name: fishing-booker-app
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          name: deploy-client
          app-name: fishing-booker-client
          requires:
            - deploy-server